version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - dependabot
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "next"
        update-types:
          - version-update:semver-major
      - dependency-name: "tailwindcss"
        update-types:
          - version-update:semver-major
      - dependency-name: "typescript"
        update-types:
          - version-update:semver-major
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - dependabot
    groups:
      github-actions:
        patterns:
          - "*"
